# Arquivo de configuração para o deploy no Netlify

[build]
  # Comando para instalar as dependências Python.
  command = "pip install -r requirements.txt"

  # Diretório que contém os arquivos estáticos (index.html).
  # "." significa a raiz do seu repositório.
  publish = "."

  # Diretório onde o Netlify procura por funções serverless.
  functions = "api/"

[[redirects]]
  # Redireciona todas as chamadas da API para a nossa função Flask.
  from = "/consulta/*"
  to = "/.netlify/functions/app/consulta/:splat"
  status = 200
