# Arquivo de configuração para o deploy no Netlify

[build]
  # Comando para instalar as dependências Python.
  command = "pip install -r requirements.txt"

  # Diretório que contém os arquivos estáticos (index.html).
  publish = "."

# Bloco dedicado para a configuração das funções serverless.
[functions]
  directory = "netlify/functions/"

# [[redirects]]
#   # Redirecionamento temporariamente desativado para depuração.
#   from = "/consulta/*"
#   to = "/.netlify/functions/cep/consulta/:splat"
#   status = 200
