# Arquivo de configuração para o deploy no Netlify

[build]
  # Comando para instalar as dependências Python.
  command = "pip install -r requirements.txt"

  # Diretório que contém os arquivos estáticos (index.html).
  publish = "."

  # Diretório onde o Netlify procura por funções serverless.
  functions = "api/"

# Adiciona uma variável de ambiente para especificar explicitamente o handler da função.
# Isso ajuda o Netlify a encontrar a aplicação Flask quando a detecção automática falha.
# "cep.app" significa: no arquivo 'cep.py', use a variável 'app'.
[context.production.environment]
  AWS_LAMBDA_EXEC_WRAPPER = "cep.app"

[[redirects]]
  # Redireciona todas as chamadas da API para a nossa função 'cep'.
  from = "/consulta/*"
  to = "/.netlify/functions/cep/consulta/:splat"
  status = 200
