# Arquivo de configuração para o deploy no Netlify

[build]
  # Comando para instalar as dependências Python.
  command = "pip install -r requirements.txt"

  # Diretório que contém os arquivos estáticos (index.html).
  publish = "."

# Bloco dedicado para a configuração das funções serverless.
# Apontando para o diretório padrão do Netlify para máxima compatibilidade.
[functions]
  directory = "netlify/functions/"

[[redirects]]
  # A regra de redirecionamento permanece a mesma, pois o Netlify
  # serve a função 'cep' no mesmo caminho público.
  from = "/consulta/*"
  to = "/.netlify/functions/cep/consulta/:splat"
  status = 200
